# Generated by Django 2.2.6 on 2020-09-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='remarks',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('CB', 'CBID'), ('NA', 'Not Available')], default='PD', max_length=2),
        ),
    ]
