# Generated by Django 2.2.6 on 2020-09-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200930_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='completed',
            field=models.BooleanField(null=True),
        ),
    ]
