# Generated by Django 2.2.6 on 2020-09-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200913_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_bilingual',
            new_name='ctc',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_ctc',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_document',
            new_name='output_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='middleware_service',
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
