# Generated by Django 2.2.6 on 2020-09-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200930_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('MS', 'Malay')], default='EN', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='output_type',
            field=models.CharField(choices=[('DO', 'Document'), ('IM', 'Image'), ('LI', 'List')], default='CP', max_length=2),
        ),
    ]
