# Generated by Django 2.2.6 on 2020-09-30 08:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('search_criteria', models.CharField(default='NA', max_length=255)),
                ('total_pages', models.IntegerField(default=51)),
                ('total_company', models.IntegerField(default=1360941)),
                ('unit_price', models.FloatField(default=30)),
                ('total_price', models.FloatField(default=30)),
                ('total', models.IntegerField(default=1)),
                ('sst', models.FloatField(default=1.8)),
                ('total_amount', models.FloatField(default=31.8)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
