# Generated by Django 2.2.6 on 2020-09-30 08:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_auto_20200930_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_gateway_order_id',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TransactionPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=100)),
                ('payment_status', models.CharField(choices=[('OK', 'Successful'), ('FL', 'Failed'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('payment_gateway_payment_id', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.Transaction')),
            ],
        ),
    ]
