# Generated by Django 2.2.6 on 2020-09-30 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_auto_20200930_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='name',
        ),
        migrations.RemoveField(
            model_name='transactionpayment',
            name='name',
        ),
    ]
