# Generated by Django 2.2.6 on 2020-09-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_auto_20200930_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='is_paid',
            new_name='paid',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='reference_no',
        ),
        migrations.RemoveField(
            model_name='transactionpayment',
            name='payment_gateway_payment_id',
        ),
        migrations.RemoveField(
            model_name='transactionpayment',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_gateway_update_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_status',
            field=models.CharField(choices=[('OK', 'Successful'), ('FL', 'Failed'), ('PD', 'Pending'), ('NA', 'Not Available')], default='PD', max_length=2),
        ),
    ]
