# Generated by Django 2.2.6 on 2020-09-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_egov_quota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('AD', 'Admin'), ('EG', 'eGovernment'), ('PB', 'Public'), ('NA', 'Not Available')], default='PB', max_length=2),
        ),
    ]
